#!/usr/bin/env bun
// Build orchestration for omp-host.exe: pack the .node files of @oh-my-pi/pi-natives into a tar.gz embedded into the compiled artifact,
// which the loader unpacks to ~/.omp/natives/<version>/ at runtime. In the npm-published pi-natives,
// embedded-addon.js is a null stub (the embed flow only exists in the upstream source repo), so a plain bun build --compile
// produces an exe without the native addon, guaranteed to fail on a clean machine.
// Flow copied from upstream ci-release-build-binaries.ts: embed -> compile -> reset (reset in finally,
// so a failed compile leaves no non-stub embedded-addon.js behind that would misclassify dev mode as compiled).
import * as fs from "node:fs/promises";
import * as path from "node:path";
import {
	containsVersionSentinel,
	versionSentinelFor,
} from "../node_modules/@oh-my-pi/pi-natives/native/version-sentinel.js";

const repoRoot = path.join(import.meta.dir, "..");
const nativesPkgDir = path.join(repoRoot, "node_modules", "@oh-my-pi", "pi-natives");
const nativeDir = path.join(nativesPkgDir, "native");
const leafPkgDir = path.join(repoRoot, "node_modules", "@oh-my-pi", `pi-natives-${process.platform}-${process.arch}`);
const embeddedAddonPath = path.join(nativeDir, "embedded-addon.js");
const platformTag = `${process.platform}-${process.arch}`;
const archiveFilename = `embedded-addons.${platformTag}.tar.gz`;
const version = (JSON.parse(await Bun.file(path.join(nativesPkgDir, "package.json")).text())).version as string;

const candidates =
	process.arch === "x64"
		? [
				{ variant: "modern", filename: `pi_natives.${platformTag}-modern.node` },
				{ variant: "baseline", filename: `pi_natives.${platformTag}-baseline.node` },
			]
		: [{ variant: "default", filename: `pi_natives.${platformTag}.node` }];

async function resetEmbeddedAddon(): Promise<void> {
	await Bun.write(
		embeddedAddonPath,
		"// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY\n// See scripts/build-host.ts\n\n/** @type {null} */\nexport const embeddedAddon = null;\n",
	);
	await fs.rm(path.join(nativeDir, archiveFilename), { force: true });
}

async function embedNativeAddon(): Promise<void> {
	await resetEmbeddedAddon();
	const sentinel = versionSentinelFor(version);
	const entries: Record<string, Uint8Array> = {};
	const files: string[] = [];
	for (const { variant, filename } of candidates) {
		const sourcePath = path.join(leafPkgDir, filename);
		const file = Bun.file(sourcePath);
		if (!(await file.exists())) continue;
		// Must be a Node Buffer: Buffer.indexOf supports substring search, Uint8Array.indexOf only matches a single byte
		const bytes = await fs.readFile(sourcePath);
		if (!containsVersionSentinel(bytes, sentinel)) {
			throw new Error(
				`${sourcePath} 不含 @oh-my-pi/pi-natives@${version} 版本哨兵 \`${sentinel}\`，依赖版本不一致，请重装依赖`,
			);
		}
		entries[filename] = bytes;
		files.push(`\t{ variant: ${JSON.stringify(variant)}, filename: ${JSON.stringify(filename)}, size: ${bytes.length} },`);
	}
	if (files.length === 0) {
		throw new Error(`${leafPkgDir} 下没有任何 native addon（期望 ${candidates.map(c => c.filename).join(" 或 ")}）`);
	}
	const archiveBytes = await new Bun.Archive(entries, { compress: "gzip", level: 9 }).bytes();
	await Bun.write(path.join(nativeDir, archiveFilename), archiveBytes);
	await Bun.write(
		embeddedAddonPath,
		`// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY\n// See scripts/build-host.ts\n\nimport archivePath from ${JSON.stringify(`./${archiveFilename}`)} with { type: "file" };\n\nexport const embeddedAddon = {\n\tplatformTag: ${JSON.stringify(platformTag)},\n\tversion: ${JSON.stringify(version)},\n\tarchive: { format: "tar.gz", filename: ${JSON.stringify(archiveFilename)}, filePath: archivePath },\n\tfiles: [\n${files.join("\n")}\n\t],\n};\n`,
	);
	console.log(`已内嵌 native addon：${files.length} 个变体，tar.gz 共 ${(archiveBytes.length / 1024 / 1024).toFixed(1)} MB`);
}

await embedNativeAddon();
try {
	const build = Bun.spawnSync(
		[
			"bun",
			"build",
			"--compile",
			"--minify",
			"--external",
			"omp-legacy-pi-modules",
			"host/host.ts",
			"--outfile",
			"host-dist/omp-host.exe",
		],
		{ cwd: repoRoot, stdout: "inherit", stderr: "inherit" },
	);
	process.exitCode = build.exitCode ?? 1;
} finally {
	await resetEmbeddedAddon();
}
